config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'download_pdf_web_dev', to: 'pages#download_pdf_web_dev'
  get 'download_pdf_consulting', to: 'pages#download_pdf_consulting'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def download_pdf_web_dev
    send_file "#{Rails.root}/app/assets/curriculums/pierre_coppermann_cv_web_dev.pdf", type: 'application/pdf', x_sendfile: true
    # redirect_to root_path
  end

  def download_pdf_consulting
    send_file "#{Rails.root}/app/assets/curriculums/pierre_coppermann_cv_consulting.pdf", type: 'application/pdf', x_sendfile: true
    # redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PcoppyHomepage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="header-image"></div>
<div class="header-background">
  <div class="header-box">
    <h1 class = "heading">I am</h1>
    <h1 class = "my-name">Pierre Coppermann</h1>
    <h2 class = "punchline">Student/Teacher/Developper</h2>
  </div>
    <div id="scrollable">
      <i class="fa-sharp fa-solid fa-chevron-down"></i>
  </div>
</div>

<div class = "profile-container">
  <div class="img-banner" id = "first">
    <div class = "profile-title">
      <h1>Place Holder
        <div class="profile-underline"></div>
      </h1>
    </div>
    <%= link_to download_pdf_consulting_path, class: "btn-download", target: :_blank do %>
      <i class="fa-solid fa-file-arrow-down download-icon" style="color: white"></i>
        <p style="color: white">download cv</p>
    <% end %>
  </div>
  <div class="img-banner" id = "second" >
    <div class = "profile-title">
      <h1>Place Holder
        <div class="profile-underline"></div>
      </h1>
    </div>
    <%= link_to download_pdf_web_dev_path, class: "btn-download", target: :_blank do %>
      <i class="fa-solid fa-file-arrow-down download-icon"></i>
        <p>download cv</p>
    <% end %>
  </div>
  <div class="img-banner" id = "third" href = "pierre_coppermann_cv_consulting.pdf" download>
    <div class = "profile-title">
      <h1>Place Holder
        <div class="profile-underline"></div>
      </h1>
    </div>
  </div>
</div>
<h1>Hello there</h1>
<%# ../../assets/curiculums/pierre_coppermann_cv_web_dev.pdf %>